### ISSUE TITLE
FM v2.68 isn't working any more on 64bit (portable) Firefox v113.0.2

### ISSUE THREAD

**Issue by pstein** [erosman/support#559] opened 2023-05-30 11:28 UTC
As I noticed FireMonkey v2.68 isn't working any more on Firefox v113.0.2
All my previous scripts are enabled but they are not applied.

Whats wrong?

**Comment by erosman** [comment] 2023-05-30 12:22
Are there any errors in FM log, Web Developer Tools, or Browser console?

Have you tested it on standard (not portable) Firefox?

Try exporting the preferences, reinstalling FM and then re-importing the preferences.

**Comment by pstein** [comment] 2023-05-31 05:47
Thankfully I had a recent backup of firefox+AddOns. So I did the following:

I updated Firefox to the newest v113.0.2 and all other ~12 AddOns (except Firemonkey v2.67) to their newest version and restarted full Firefox (on Win 10).
Result: Firemonkey scripts work (as usual)

Now I updated Firemonkey v2.67 to .v2.68 and restarted Firefox.
Result: None of my Scripts work any more

So Firemonkey is the culprit

And (as fas a s I can see) 
- ALL scripts do not work
- All the instructions inside do not work (even not partially)

Exporting preferences + reinstalltion + re-importing does not help.

Curiously downgrading FireMonkey from v2.68 down to v.2.67 does not help either.

Web Developer Tools does not show any extraordinary messages.
Where can I find Firefox log?
I guess I disabled logging somewhere in past.

**Comment by erosman** [comment] 2023-05-31 06:01
Try FireMonkey 2.68 with the previous version of Firefox portable (before 113).

Where did you get the portable version?

**Comment by Tristar7** [comment] 2023-06-02 23:38
similar here, FM works but GM_setValue erratically fails. Drove me crazy to debug but sure enough an "update" causes it, back to 2.87 all works fine again.

**Comment by erosman** [comment] 2023-06-03 04:08
> similar here, FM works but GM_setValue erratically fails. Drove me crazy to debug but sure enough an "update" causes it, back to 2.87 all works fine again.

That appear to be a different issue.

The main difference in `GM_setValue` between 2.67 & 2.68 is that the process is carried out in the content script instead of background script.

It should not make any difference but, I will do some some testing and it it is causing issues, I will change it back to the background process.

**Comment by erosman** [comment] 2023-06-03 10:03
v2.70 released
- Moved `GM setValue` & `GM deleteValue` back to the background script

**Comment by 2t9z16yo** [comment] 2023-06-05 03:33
i also had a problem with a couple of scripts not working on 2.68 and 2.69 and now fixed with 2.70. it must have been the issue with GM setvalue

**Comment by pstein** [comment] 2023-06-05 11:05
I tried FF 112.0 together with FM v2.68 and 2.70 --->All scripts not working

So altogether this is the current situation:

FF v112.0 + FM 2,67  working
FF 113.0.2 + FM 2.67 working
FF 112.0 + FM v2.68....v2.70 NOT working
FF 113.0.2 + FM v2.68.....v2.70 NOT working

So the problem is obviously in FM

**Comment by erosman** [comment] 2023-06-05 11:08
- Can you give me a script to test?
- Are they working on normal Firefox (release, beta, dev, Nightly)?
- Is the problem only on Firefox portable?

**Comment by pstein** [comment] 2023-06-06 05:16
I found a (work around):

After update of FM v2.67 to v2.70 all scripts are NOT working any more as already said.

But then I dragged all the *.user.js scripts again from File Explorer scripts backup directory onto Firefox. In other words: I re-installed them.

....and that make the scripts working again even with FF 113.0.2 and FM v2.70.
At least as far as I can see.

Not sure what the reason is. Maybe FM corrupts existing (!) scripts in its cache when updating from v2.67 to newer version..
So re-dragging *.user.js scripts is only a work around but I suggest to investigate the reason

**Comment by erosman** [comment] 2023-06-06 05:53
> Not sure what the reason is. Maybe FM corrupts existing (!) scripts in its cache when updating from v2.67 to newer version..
So re-dragging *.user.js scripts is only a work around but I suggest to investigate the reason

That is possible to be the cause. Browser caches the addons. Sometimes the upgrade is not applied properly thus ending up with some files from a previous version. As mentioned before, there was another similar report in #556.

In such cases (for any extension):

- Export Preferences
- Uninstall FireMonkey
- Restart the browser (sometimes necessary to restart with all extensions disabled to clear the cache)
- Reinstall FireMonkey
- Import Preferences

**Comment by Altair2009** [comment] 2023-06-13 21:41
> 
> That is possible to be the cause. Browser caches the addons. Sometimes the upgrade is not applied properly thus ending up with some files from a previous version. As mentioned before, there was another similar report in #556.
> 
> In such cases (for any extension):
> 
>     * Export Preferences
> 
>     * Uninstall FireMonkey
> 
>     * Restart the browser (sometimes necessary to restart with all extensions disabled to clear the cache)
> 
>     * Reinstall FireMonkey
> 
>     * Import Preferences

not having the same issue but can help some one. 
I was having a memory leak with a script that steps help determine wich one was. when i opened on a notepad i see that 1 script was  like half millon lines of "exclude" pages (have 5 excluded pages) repeting himself making a file of 30mb

**Comment by erosman** [comment] 2023-06-14 04:51
> I was having a memory leak with a script ...

Poorly written scripts do affect browser performance.
That can happen even with a script that has a few lines. 

I have also seen them in addons when I was reviewing the addons for Mozilla.
A poorly written loop can crash/hang the browser.
Another example that I have seen, was the following which was running a function 1000 times per second.

```js
setInterval(someFunction, 1);
```

**Comment by erosman** [comment] 2023-06-25 08:34
What is the outcome of reinstalling?

**Closed** 2023-07-10 12:06 UTC
Labels: addon: FireMonkey
