### ISSUE TITLE
Copy PlainText: There was an error with the operation.

### ISSUE THREAD

**Issue by pot08** [erosman/support#291] opened 2021-02-26 21:00 UTC
I've been using your awesome FF extension well since you answered me about the shortcut 3-4 years ago. Thank you from the bottom of my heart.

I'm using a shortcut Alt+1(no override at all), but sometimes it doesn't work like this site: [naver blog](https://blog.naver.com/lecroykorea/222238852539). On the other hand, it works(of course different tags) on the [same flatform](https://blog.naver.com/2fineday/220963659521): when copying the url on the article. A strange thing is it works well whatever the site is when using "Copy PlainText" from a drop-down menu (right-click).

I'm not sure what is the problem and if writing like this would observe community guidelines. I’m sorry for any offense that I might've caused. Thank you.

**Comment by erosman** [comment] 2021-02-26 21:55
No problem.

There is a fundamental difference between the process when using context-menu & keyboard shortcut

- Context-menu gets the selected text directly (up to 16,384 characters)
- Keyboard shortcut has to get the selected text by injecting a script into the page to get it

When injecting a script into the page to get the selected text, the script is subject to the page limitations, for example:
- Script injection into some pages are blocked by Firefox e.g. `addons.mozilla.org`
- Page CSP (Content Security Policy) as well as some page JavaScript can interfere with the process
 
That is the reason there can be errors.

I tested `https://blog.naver.com/2fineday/220963659521` and the keyboard shortcut doesn't get the selected text and therefore gives an error.

I will do some more test to see if anything can be done

**Comment by erosman** [comment] 2021-02-27 13:48
Actually the issue with `https://blog.naver.com/2fineday/220963659521` is that the page is inside an `iframe`.

I will work something out.

**Comment by erosman** [comment] 2021-03-04 06:29
I have uploaded v1.12 which would be available soon.
Let me know if that solves the issue.

**Comment by pot08** [comment] 2021-03-14 22:57
Thank you for your quick response and great kindness. I have tested in some OS and some FF versions but unfortunately the 1.12 version still doesn't work for now (like this [page](https://blog.naver.com/energyinfoplaza/222265047956), [page](https://blog.naver.com/lecroykorea/222238852539), [page](https://blog.naver.com/2fineday/220963659521)).

**Comment by erosman** [comment] 2021-03-15 06:33
I test all 3 above page.

- ✅ works with context-menu
- ✅ works with keyboard shortcut if JavaScript is disabled on the page
- ❌ doesn't works with keyboard shortcut if JavaScript is enabled on the page

The problem is that those pages intentionally use JavaScript to limit users. At the moment, there is no way round that. You would need to use context-menu as getting the text with the keyboard shortcut gets blocked by the page.

**Comment by formlessdao** [comment] 2021-07-14 09:26
erosman how do I set up shortcuts for your extensions? Or better yet what are the shortcuts for your extensions? 
I can't find Text Multicopy shortcuts listed anywhere.

**Comment by erosman** [comment] 2021-07-14 11:19
> how do I set up shortcuts for your extensions? Or better yet what are the shortcuts for your extensions?
I can't find Text Multicopy shortcuts listed anywhere.

F7 is the default shortcut for **Copy PlainText** and F8 for **Text MultiCopy**.

As per included Help:

> **Manage extension shortcuts in Firefox**
> 
> You can now change your extensions' keyboard shortcuts on the add-ons page.
> 
> - Click the menu button ☰;, click Add-ons and select Extensions (Add-ons and themes in newer Firefox).
> - Click the Tools for all add-ons cogwheel.
> - Click Manage Extension Shortcuts in the menu.
> - You will see the shortcut options (if available) for your installed add-ons.
> 
> [Manage extension shortcuts in Firefox](https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox)

**Comment by erosman** [comment] 2023-07-03 09:45
It seems to be the same Firefox bug as in issue #216.

It should be fixed in v1.14.

**Closed by erosman** 2023-07-03 09:45 UTC
Labels: addon: Copy PlainText
