### ISSUE TITLE
match applies to page, but it is listed in "Other scripts and CSS"

### ISSUE THREAD

**Issue by ryanmk54** [erosman/support#287] opened 2021-02-18 17:07 UTC
I'm using this match, `@match *://*.localhost/*` to change this url `http://localhost:3000/ap_vendors`. The style is applied to the page, but it is listed in "Other scripts and CSS". I thought styles applied to the page would be listed in "Tab scripts and CSS".

**Comment by erosman** [comment] 2021-02-18 17:43
`http://localhost:3000/ap_vendors` is not a valid match pattern.

> [Invalid match patterns](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns#invalid_match_patterns)
> 
> |Invalid pattern|Reason
> |---|---|
> |`https://mozilla.org:80/`|Host must not include a port number. |
> 


>  I thought styles applied to the page would be listed in "Tab scripts and CSS".

It should but they use different processes. The injection is done by Firefox while the listing in popup is created by FireMonkey.

So, you are using `@match *://*.localhost/*`?
I will check where the problem is and fix it.

**Comment by erosman** [comment] 2021-02-18 18:01
I tested with `@match *://*.localhost/*` and it comes up under **Tab Scripts & CSS**

**Comment by ryanmk54** [comment] 2021-02-18 19:58
Sorry, I didn't explain very well. Here are some screenshots to help.
![Screenshot 2021-02-18 125239](https://user-images.githubusercontent.com/1811468/108413766-a6387000-71e8-11eb-9ce5-bfa69bc7df15.png)
![Screenshot 2021-02-18 125702](https://user-images.githubusercontent.com/1811468/108413914-d6800e80-71e8-11eb-8429-b28a4e2a8061.png)

**Comment by erosman** [comment] 2021-02-18 20:12
I see ...... Let me work on it then.

**Comment by erosman** [comment] 2021-02-18 20:36
Fixed. It will be in the update v2.19

**Closed by erosman** 2021-02-18 20:36 UTC
