### ISSUE TITLE
User style changes are not applied to the loaded page

### ISSUE THREAD

**Issue by ygoe** [erosman/support#417] opened 2022-01-24 20:20 UTC
When I edit a style, I want to see if it works. With Stylus, the changed style is applied instantly. With FireMonkey, it is never applied. I have to reload the page to see the changes of my style code.

The same applies to activating or deactivating user styles from the extension menu.

**Comment by erosman** [comment] 2022-01-25 05:09
Duplicate of #295

**Closed by erosman** 2022-01-25 05:09 UTC
Labels: duplicate
