### ISSUE TITLE
Tabs closing too easily with keyboard

### ISSUE THREAD

**Issue by ryanfeeley** [erosman/support#271] opened 2021-01-07 12:42 UTC
I've noticed in recent months that when closing tabs on a MacBook Pro by ⌘W that two will close instead of one. 

Firefox 84.0.1 (64-bit)

I have experimented by disabling the FoxyTab, and it goes away.

It is difficult to reproduce unfortunately. It's not every time.

**Comment by erosman** [comment] 2021-01-07 13:13
FoxyTab doesn't have any keyboard listeners to listen to keyboard actions. I suspect the issue is elsewhere.

Also check by going to 

_about:addons -> ⚙️ -> Manage Extension Shortcuts_

**Comment by erosman** [comment] 2022-04-09 08:11
v2.16 will be released soon.
Let me know if there are still issues.

**Closed by erosman** 2022-04-09 08:11 UTC
