### ISSUE TITLE
[FireMonkey] Somehow userscript interferes with sites' favicon

### ISSUE THREAD

**Issue by Purfview** [erosman/support#572] opened 2023-07-11 21:27 UTC
Somehow userscript interferes with sites' favicon.

Userscript: https://github.com/Purfview/IMDb-Scout-Mod
Site: https://www.imdb.com/title/tt0088247/reference
Relevant link: https://github.com/Purfview/IMDb-Scout-Mod/issues/180

Issue:
IMDb's favicon in a tab blinks multiple times and changes to some random icon from the script.

**Comment by erosman** [comment] 2023-07-12 05:32
FireMonkey has no function relating to a site's favicon. The favicon change relates to the userscript.

**Comment by Purfview** [comment] 2023-07-12 08:06
The userscript has no function relating to the site's favicon too and bug doesn't happen with any other "Monkey."

Here how it looks:

![alt text](https://i.imgur.com/F7m9R3i.png)

[Changes to a random image from the script, sometimes in the end it changes back to the original]

Here that icon starts as variable: [IMDb_Scout_Mod.user.js#L8754](https://github.com/Purfview/IMDb-Scout-Mod/blob/2ce6f73258d53b25c89d932052f2b5334d3f535f/IMDb_Scout_Mod.user.js#L8754)
Here that icon ends going to the custom `.LetterboxdUserRatingImg` element: [IMDb_Scout_Mod.user.js#L9114](https://github.com/Purfview/IMDb-Scout-Mod/blob/2ce6f73258d53b25c89d932052f2b5334d3f535f/IMDb_Scout_Mod.user.js#L9114)

**Comment by erosman** [comment] 2023-07-12 08:24
I also noticed the favicon change but without checking the userscript in detail, the cause is unclear.

If the userscript developer points out the reason and it is related to FireMonkey, I will fix it.

**Comment by Purfview** [comment] 2023-07-12 08:41
I'm the developer. I don't see any reason from the userscript's side.

This - `$('.LetterboxdUserRatingImg').attr('src', lboxd_icon);` somehow changes the favicon.
`LetterboxdUserRatingImg` is custom unique element, it shouldn't interfere with favicon.

**Comment by erosman** [comment] 2023-07-12 08:50
@Purfview Thank you for replying.

I have noticed Firefox sometimes changes favicon relating to HTTP request made from a page..
That should not happen but it sometimes does. I am going to have a chat with Mozilla engineers about it.

**Comment by erosman** [comment] 2023-07-12 11:15
I have been doing some testing and here is the log of the code that requests the favicon.
I see a few favicon changes as the script executes.

```
load
resource:///modules/FaviconLoader.sys.mjs:176:20
load
resource:///modules/FaviconLoader.sys.mjs:563:70
loadIcons
resource:///modules/FaviconLoader.sys.mjs:641:26
FaviconLoader/this.iconTask<
resource:///modules/FaviconLoader.sys.mjs:617:18
_runTask
resource://gre/modules/DeferredTask.sys.mjs:347:18
_timerCallback/<
resource://gre/modules/DeferredTask.sys.mjs:318:20
_timerCallback
resource://gre/modules/DeferredTask.sys.mjs:337:9
_startTimer/callback/<
resource://gre/modules/DeferredTask.sys.mjs:185:18
```

**Comment by erosman** [comment] 2023-09-29 05:25
Firefox bug is fixed in Firefox 120

See also: 
[Bug 1843267: Favicons defined in disconnected link elements (in document fragments) will be loaded and used as the tab icon](https://bugzilla.mozilla.org/show_bug.cgi?id=1843267)

**Closed by erosman** 2023-09-29 05:25 UTC
Labels: 🦊 Firefox Bug, addon: FireMonkey, userscript: help
