### ISSUE TITLE
'userutils not defined'

### ISSUE THREAD

**Issue by Gl17chV** [erosman/support#659] opened 2024-10-17 15:12 UTC
Hi dev, I added this script on FireMonkey https://greasyfork.org/en/scripts/475682-betterytm
but it fails to insert due to _'UserUtils is not defined'_ do you know why?

**Comment by erosman** [comment] 2024-10-17 15:24
That userscript generates too many error to pin point the cause.

**Comment by Gl17chV** [comment] 2024-10-17 21:46
:/ So there's nothing I can do?

**Comment by erosman** [comment] 2024-10-17 21:56
The script is too large to debug. You can ask the userscript developer. He might be able to find out the reason.

**Comment by Sv443** [comment] 2024-10-18 13:57
Hi, author here, I've just tested with a tiny script and came to the conclusion that loading `@resource` directives via `GM.getResourceUrl` doesn't work at all in FireMonkey.  
The function itself exists, but the Promise always resolves to an error, without any hint as to what is going wrong:  

<details><summary>Script source - click to expand</summary>

```js
// ==UserScript==
// @name             FM resource test
// @match            *://*.example.org/*
// @version          1.0
// @resource         abc https://raw.githubusercontent.com/Sv443/BetterYTM/v2.1.0/assets/translations/en_US.json
// @grant            GM.getResourceUrl
// ==/UserScript==

(async () => {
  console.log("GM", GM);
  console.log("GM.getResourceUrl", GM.getResourceUrl);
  console.log(`GM.getResourceUrl("abc")`, GM.getResourceUrl("abc"))
  console.log(`await GM.getResourceUrl("abc")`, await GM.getResourceUrl("abc"))
})();
```

</details>

![image](https://github.com/user-attachments/assets/b1ea309d-75f8-4335-ba8d-c2237f1bc993)

**Comment by erosman** [comment] 2024-10-18 15:04
There is a typo bug in FireMonkey. It should be `resources`. 
It is fixed in v2.73.

https://github.com/erosman/support/blob/a2a73577c2bfecbeda8b708ec429f60e252aadf5/content/api.js#L4

https://github.com/erosman/support/blob/a2a73577c2bfecbeda8b708ec429f60e252aadf5/content/api.js#L215-L217

https://github.com/erosman/support/blob/a2a73577c2bfecbeda8b708ec429f60e252aadf5/content/api.js#L653-L655

**Comment by Sv443** [comment] 2024-10-18 20:30
Alright thanks, I'll verify everything once it's released.

**Comment by erosman** [comment] 2024-11-11 12:10
FireMonkey v2.73 released.

**Comment by Sv443** [comment] 2024-11-11 12:36
Thank you very much, I can confirm the bulk of the errors is gone, but now I have a new one to report: #664

**Closed** 2024-12-06 06:25 UTC
Labels: bug 🐞, done ✓, userscript: compatibility, addon: FireMonkey
